apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginxdeploy
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: nginxpod
  template:
    metadata:
      name: nginxpod
      labels:
        app: nginxpod
    spec:
      containers:
        - name: nginxcontainer
          image: nginx:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
