apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  password: bXlwYXNzd29yZAo=

---

apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mysqldeployment
  labels:
    app: mysql
spec:
  replicas: 3 
  minReadySeconds: 10
  revisionHistoryLimit: 5 
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 2 
  template:
    metadata: 
      name: mysql_pod
      labels: 
        app: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          emptyDir: {}
